<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>ChefKnifeStudios.PokerAttack.Client.Shared</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MatBlazor" Version="2.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
    <PackageReference Include="NameGenerator" Version="2.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChefKnifeStudios.PokerAttack.Client.Core\ChefKnifeStudios.PokerAttack.Client.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EventArgs\ModalEventArgs\" />
  </ItemGroup>

</Project>
